[project]
name = "say-hello"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dashscope>=1.22.2",
    "gradio-client>=1.8.0",
    "mcp[cli]>=1.5.0",
]
